In [3]:
import numpy as np

In [7]:
a = np.arange(10, dtype = int)

for i in a:
    print(a[i])

0
1
2
3
4
5
6
7
8
9


- arange(start, end, stepper, dtype) 

    start :- starting value

    end :- ending value exclusive
    
    stepper :- spacing between values
    
    stype :- data type
    
arange is numpy method of creating 1-d array.

In [9]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [14]:
b = np.linspace(3, 10, 5, dtype = int, endpoint = False)
b

array([3, 4, 5, 7, 8])

In [17]:
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
b = np.random.rand(4)
b

array([0.40323184, 0.27095382, 0.43836199, 0.17171892])

In [23]:
b = np.random.rand(2,3)
b

array([[0.48786736, 0.86127235, 0.67861171],
       [0.5714798 , 0.89577372, 0.13533266]])

In [26]:
b = np.random.randint(2,6)* 10 
b

30

In [28]:
b = np.arange(9,50)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [35]:
b = np.identity(5)
b


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])