In [1]:
import numpy as np

a = np.random.randint(5,20,5)
b = np.random.randint(2, 20, 5)

print(a)
print(b)

[14 17 19 12  8]
[ 9  3  6 12 13]


In [3]:
c = a + b
c

array([23, 20, 25, 24, 21])

In [4]:
a = a + 1
a

array([15, 18, 20, 13,  9])

In [5]:
d = a - b
d

array([ 6, 15, 14,  1, -4])

In [6]:
e = a*b
e

array([135,  54, 120, 156, 117])

In [7]:
f = a ** b
f

array([ -211346289,        5832,    64000000, -2112458319,  -754810903],
      dtype=int32)

In [9]:
g = a // b
g 

array([1, 6, 3, 1, 0], dtype=int32)

In [10]:
h = a / b
h


array([1.66666667, 6.        , 3.33333333, 1.08333333, 0.69230769])

In [12]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[15 18 20 13  9]
75
15.0
9
4
20
2


In [17]:
# logical opearations

q = np.logical_and(a,b)
print(q)
r = np.logical_or(a,b)
print(r)
s = np.logical_not(a,b)
print(s)

[False False False False False]
[ True  True  True  True  True]
[1 1 1 1 1]


In [21]:
# relational operations

v = a >= 10
print(v)

[False False False False False]
